# Dependencies
highlighter:      rouge

# Config
gems: [jekyll-gist,jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            Kat is Awesome and AMAZING
tagline:          'Summer quarter 2016'
description:      This is a wonderful website. Yep.
url:              http://digitalframeworks.github.io
baseurl:          /

author:
  name:           'kat lonsdorf'
  url:            https://twitter.com/lilkat_bigworld

paginate:         15

exclude: [node_modules]

sass:
  sass_dir: _sass
  style: compressed

# Custom vars
navlinks:
- url: https://nwudigitalframeworks.slack.com/messages/general/
  title: Slack
- url: mailto:davideads@gmail.com
  title: Email
